services:
  web:
    image: fprochazka/filip-prochazka-com:latest
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /srv
    volumes:
      - ./:/srv
    ports:
      - "127.0.0.1:4000:4000"
    command: sh -c 'bundle install && rake run'
